/* One-line takeaways — closes AUDIT #15.
   The explanations teach the reasoning well, but the retrievable unit — the rule you carry
   into the next question — was buried in prose. Each line here is the rule alone, shown
   above the explanation so it can be absorbed in two seconds.
   Attached by id so the question files stay untouched. */
(function(){
  var T = {

/* ================= NUMERICAL ================= */
'num-0':"Percentage change always divides by the OLD value.",
'num-1':"To undo a discount, divide by (1 − rate). Never add the rate back.",
'num-2':"Successive percentages multiply: +20% then −20% leaves 0.96, not 1.00.",
'num-3':"To reverse an increase, divide by (1 + rate).",
'num-4':"'A is x% more than B' and 'B is x% less than A' are different numbers — the base flips.",
'num-5':"If x is 1/n of y, then y is n × 100% of x.",
'num-6':"A reduction is measured against the figure you started from.",
'num-7':"Reversing a +x% always needs a smaller −%, because it comes off a larger base.",
'num-8':"Two-step percentages: compute the intermediate value first, then the second ratio.",
'num-9':"Margin divides by PRICE. Markup divides by COST.",
'num-10':"If costs are c% of revenue, profit is simply (100 − c)% of revenue.",
'num-11':"Chain the multipliers: markup × discount in one line, 1.40 × 0.75 = 1.05.",
'num-12':"A blended margin is weighted by revenue share, never the simple average.",
'num-13':"Break-even units = fixed costs ÷ contribution per unit, not ÷ price.",
'num-14':"When the margin is a ratio, break-even revenue = fixed costs ÷ that ratio.",
'num-15':"Costs are the complement of margin: 15% margin means costs are 85% of revenue.",
'num-16':"Turn a cost:revenue ratio into a fraction of revenue before computing profit.",
'num-17':"Reduce to a unit rate (per machine per hour) and every combination is one multiplication.",
'num-18':"People × days is constant. More people means proportionally fewer days.",
'num-19':"Convert to worker-hours per unit of output; it handles changes on both sides at once.",
'num-20':"Working together, ADD the rates. Never average the times.",
'num-21':"Average speed = total distance ÷ total time. Never average the two speeds.",
'num-22':"Multiply the chain of rates in whichever order gives the friendliest intermediate.",
'num-23':"Find the unit rate first; it turns two unknowns into one division.",
'num-24':"Convert averages into sums before adding or removing any item.",
'num-25':"A joiner's value = new total − old total.",
'num-26':"Weighted average: total cost ÷ total units, never the midpoint of the two prices.",
'num-27':"A blended return sits nearer the value carrying the larger weight.",
'num-28':"Shortcut: spread the newcomer's excess over the new headcount to get the shift.",
'num-29':"Solve for the value of ONE ratio unit, then multiply.",
'num-30':"Sum the ratio terms first; that total is what divides into the whole.",
'num-31':"Percentages of percentages multiply: 60% then 25% is 15% of the whole.",
'num-32':"Weight each subgroup by its size — averaging two rates only works if the groups are equal.",
'num-33':"Compound growth multiplies factors: P × (1 + r)ⁿ.",
'num-34':"Simple interest is always computed on the ORIGINAL principal.",
'num-35':"The gap between simple and compound interest is interest earned on interest.",
'num-36':"Doubling under compounding takes fewer years than 100% ÷ rate suggests. Rule of 72.",
'num-37':"CAGR = (end ÷ start)^(1/n) − 1. Over two years, take the square root.",
'num-38':"Declining-balance depreciation multiplies by (1 − r) each year and never reaches zero.",
'num-39':"Market share = own units ÷ total market units.",
'num-40':"Share rises only if your growth EXCEEDS the market's. Growing and losing share is normal.",
'num-41':"Inventory turnover = COGS ÷ average inventory. Rearrange for whichever term is missing.",
'num-42':"Compute the total from the parts; a share can never be read off directly.",
'num-43':"Successive raises compound — the second applies to the already-raised salary.",
'num-44':"Revenue = price × volume, so combine the two percentage moves by multiplying.",
'num-45':"A price cut is measured against the original price.",
'num-46':"Cancel trailing zeros before dividing; it removes most of the arithmetic risk.",
'num-47':"Without replacement, BOTH numerator and denominator shrink on the second draw.",
'num-48':"For 'exactly k of n', count the arrangements, not just the outcomes.",
'num-49':"Inclusion–exclusion: the amount the parts overshoot the whole IS the overlap.",
'num-50':"Unordered pairs from n items = n(n − 1) ÷ 2.",
'num-51':"Check which components the question includes — fees plus expenses, or fees alone.",
'num-52':"Markup then discount collapses into a single multiplier: 1.5 × 0.8 = 1.2.",
'num-53':"Work with the difference in percentages rather than computing both figures.",
'num-54':"A price rise beats a subscriber loss whenever the multipliers exceed 1.",
'num-55':"Contribution per unit × volume − fixed costs. Skip revenue and total variable cost entirely.",
'num-56':"Read which base the rate applies to — opening assets or year-end assets.",
'num-57':"When revenue grows faster than costs, profit swings far more than either. Operating leverage.",
'num-58':"Apply the after-tax multiplier (0.70) rather than computing the tax and subtracting.",
'num-59':"Combine the monthly factors first; 1.20 × 0.75 = 0.90 gives the answer in one step.",
'num-60':"Never assume 100% utilization — billable hours are a fraction of available hours.",
'num-61':"To price for a target margin: price = cost ÷ (1 − margin). Adding the margin to cost is wrong.",
'num-62':"Protecting the largest cost category forces a much steeper cut on everything else.",
'num-63':"Simple payback = investment ÷ annual profit.",
'num-64':"Average price = revenue ÷ units. Volume up but revenue up less means price fell.",
'num-65':"When costs grow faster than revenue, profit shrinks even though both rise.",
'num-66':"Difference the terms first; differences rising by a constant signal a quadratic.",
'num-67':"Large numbers shrinking fast: test division before hunting for a difference pattern.",
'num-68':"If a term equals the sum of the two before it, the rule is Fibonacci-style.",
'num-69':"Falling series use the same method — difference first, then look for the pattern.",
'num-70':"Differences that double signal a multiply-then-add rule, not a simple ratio.",
'num-71':"When the ratio itself changes systematically, the divisor is incrementing.",
'num-72':"Differences that are consecutive odd numbers mean the terms are n² ± k.",
'num-73':"Differences growing by a constant amount mean a quadratic pattern.",
'num-74':"A ratio that rises by exactly one each step means factorials.",
'num-75':"Error-spotting: test the rule against EVERY term, not only the last.",
'num-76':"Round to friendly numbers, then adjust for the direction you rounded.",
'num-77':"Know which way your rounding pushed the answer; it decides between close options.",
'num-78':"×19 is ×20 minus one lot. Multiply by a round number and adjust.",
'num-79':"Compare each fraction against 1/2 rather than finding a common denominator.",
'num-80':"10% a year compounds to about ×1.33 over 3 years and roughly ×2 over 7.",
'num-81':"Anchor on the nearest simple fraction — a half, a quarter, a third — then adjust.",

/* ================= WORKING WITH DATA ================= */
'data-0':"Percentage growth off a small base looks dramatic and often means little.",
'data-1':"Group the addition into friendly pairs to cut arithmetic slips.",
'data-2':"Compute the total yourself; a share is almost never given in the table.",
'data-3':"Growth divides by the earlier period, always.",
'data-4':"A segment gains share if and only if it grows faster than the total.",
'data-5':"Applying the market's growth rate to a segment shows what it 'should' have reached.",
'data-6':"Total profit = units × per-unit profit. Fewest units can still lead.",
'data-7':"Margin % = (price − cost) ÷ price. A high price does not mean a high margin.",
'data-8':"Revenue must be computed per line (units × price) before totalling.",
'data-9':"A blended margin is dragged toward whichever line carries the most revenue.",
'data-10':"Highest volume and highest revenue share are different things when prices differ.",
'data-11':"Per-employee cost isolates wage effects from the effect of simply hiring more people.",
'data-12':"Growth divides by the starting figure, not the ending one.",
'data-13':"Compare the growth of two related series to explain a ratio's movement.",
'data-14':"Check the units in the header before scaling — thousands change the answer by 1,000×.",
'data-15':"Convert 1% of the total into money once; every other share becomes trivial.",
'data-16':"Use the difference in shares rather than computing both revenues.",
'data-17':"Combined top-player share is the standard first read on market concentration.",
'data-18':"Shares add when the total market is unchanged and no customers are lost.",
'data-19':"Compute the total from the table rather than assuming a round number.",
'data-20':"Excluded categories (neutral) leave both sides of a ratio cleaner than the percentages suggest.",
'data-21':"Read whether the threshold covers one category or several before judging pass or fail.",
'data-22':"Added responses raise the denominator as well as the numerator.",
'data-23':"Dollars and percentages can rank the same items differently.",
'data-24':"Pair the figures to make a four-way addition easy.",
'data-25':"Check which profit line the question names — gross stops one line too early.",
'data-26':"Operating margin subtracts operating expenses too; gross margin does not.",
'data-27':"Sequential growth divides by the earlier quarter.",
'data-28':"Costs rising more slowly than revenue means the ratio improves. Operating leverage.",
'data-29':"Headcount × average salary per department; departmental averages cannot be added.",
'data-30':"A company-wide average must be weighted by headcount, not averaged across departments.",
'data-31':"A department's share of payroll differs from its share of headcount whenever salaries differ.",
'data-32':"Only the changed line needs recomputing; leave the rest of the table alone.",
'data-33':"Similar absolute additions produce falling percentage growth as the base grows.",
'data-34':"CAGR takes the nth root of the total growth factor, not the arithmetic mean.",
'data-35':"Read carefully for the increase versus the ending level.",
'data-36':"A constant growth RATE is not a constant addition.",
'data-37':"Absolute and percentage rankings differ — check which the question asks for.",
'data-38':"Scanning for the single declining line is the fastest first read of a cost table.",
'data-39':"Compute the total first; no share can be read straight off the table.",
'data-40':"A component's share holds constant when it grows at exactly the total's rate.",
'data-41':"A round base makes the total a free check on your column addition.",
'data-42':"Isolate the changing line rather than recomputing the whole table.",
'data-43':"Applying a growth rate again is compound; adding the absolute increase is linear.",
'data-44':"Largest by headcount and largest by cost are different questions.",
'data-45':"The lowest COGS ratio always corresponds to the highest gross margin.",
'data-46':"Mean = sum ÷ count, and it is pulled hard by a single extreme value.",
'data-47':"The median must be read from the SORTED list.",
'data-48':"The mode is the only average that is always a real observed value.",
'data-49':"When a distribution is skewed, the median describes the typical case honestly; the mean does not.",
'data-50':"Range depends entirely on the two most extreme observations.",
'data-51':"Removing an outlier moves the mean sharply and the median barely at all.",
'data-52':"Equal means can hide completely different spread.",
'data-53':"Predictability is about variability, not level — always report spread alongside the average.",
'data-54':"Correlation gives strength and direction only. Never causation, never a percentage.",
'data-55':"Strength is |r|; the sign is only direction. −0.78 beats +0.60.",
'data-56':"Look for the confounder before accepting any causal reading of a correlation.",
'data-57':"Validate dates: a month above 12 means the day/month order was swapped upstream.",
'data-58':"Identical customer, value and date under a different ID is a duplicate record.",
'data-59':"A negative order value is a refund or a sign error, never a sale.",
'data-60':"Clean before you compute — a duplicate and a negative distort both parts of an average.",
'data-61':"Shares of a whole must sum to 100%. Checking takes five seconds.",
'data-62':"Surveying only current customers excludes exactly the people who left unhappy.",
'data-63':"Missing values: investigate, choose a treatment, and disclose it. Never silently fill them.",
'data-64':"Check where the axis starts before trusting any visual comparison.",
'data-65':"Mixed units inside one column make every total meaningless.",
'data-66':"A single site is a sample of one — suggestive, not evidence.",

/* ================= CRITICAL THINKING ================= */
'ct-0':"To weaken a causal claim, supply an alternative cause acting at the same time.",
'ct-1':"If the groups differ before the treatment, the difference is selection, not effect.",
'ct-2':"A second change in the same period competes for the credit.",
'ct-3':"Competitive admission means the outcome reflects who got in, not what was added.",
'ct-4':"Raw outcome rates must be adjusted for how severe the cases were.",
'ct-5':"Voluntary participation signals pre-existing intent; forcing it transfers nothing.",
'ct-6':"Ask whether the causation could run the other way.",
'ct-7':"A large simultaneous shift in the population can account for the whole effect.",
'ct-8':"Random assignment is the strongest possible support: it breaks the selection effect.",
'ct-9':"A comparable group without the treatment is the gold-standard control.",
'ct-10':"A within-organisation comparison rules out company-wide factors.",
'ct-11':"Randomisation plus a measured outcome establishes causation, not just correlation.",
'ct-12':"Ruling out the leading alternative explanation is what strengthening means.",
'ct-13':"Comparison cases that did not change serve as the counterfactual.",
'ct-14':"Negate the option: if the argument collapses, it was the necessary assumption.",
'ct-15':"A plan that works through behaviour change assumes the behaviour actually changes.",
'ct-16':"Generalising from a survey assumes respondents resemble the whole population.",
'ct-17':"Revenue growth and investor return are different things; the gap must be bridged.",
'ct-18':"Before-and-after causal claims assume nothing else changed at the same time.",
'ct-19':"A per-unit saving assumes the number of units does not rise to cancel it.",
'ct-20':"Contrapositive: 'promoted → certified' gives 'not certified → not promoted'.",
'ct-21':"From 'all A are B' plus 'some A are C', you get 'some B are C'.",
'ct-22':"A percentage above half licenses 'most' and nothing stronger.",
'ct-23':"Modus tollens: given 'if P then Q' and 'not Q', conclude 'not P'.",
'ct-24':"A necessary condition lets you infer backwards from the outcome to the requirement.",
'ct-25':"'Rose every quarter' means each exceeded the last, so the final one is the largest.",
'ct-26':"'Only X may Y' means Y requires X — but X does not guarantee Y.",
'ct-27':"A trait shared by successful people is not thereby the cause of their success.",
'ct-28':"Attacking the author instead of the argument is a genetic fallacy.",
'ct-29':"A false dilemma presents two options when more exist.",
'ct-30':"An average tells you nothing about the typical case unless you know the distribution.",
'ct-31':"Self-selected respondents cannot support a claim about the whole group.",
'ct-32':"A straw man refutes an exaggerated version of the opponent's position.",
'ct-33':"Resolve a paradox by finding the second channel — here, revenue outside the base price.",
'ct-34':"A cost that cannot be cancelled persists no matter how usage changes.",
'ct-35':"Shelf space is zero-sum: promoting one item demotes another.",
'ct-36':"Unemployment is a ratio; the denominator can move independently of the numerator.",
'ct-37':"Revenue up but profit down means the answer is on the cost side.",
'ct-38':"Labour cost depends on wages AND productivity together.",
'ct-39':"A price rise raises profit only if the volume lost stays small enough.",
'ct-40':"Check whether the metric being reduced is the same thing as the goal.",
'ct-41':"Beating no treatment is a low bar; the decision needs a comparison with the alternative.",
'ct-42':"'More' is ambiguous between percentage points and percent — specify which.",
'ct-43':"2% to 3% is one percentage POINT but a 50% relative increase.",
'ct-44':"A raw count is meaningless without its base; compute the rate.",
'ct-45':"A gain and an equal-percentage loss never cancel; you always end below.",
'ct-46':"A confounder that causes both variables makes the association spurious.",
'ct-47':"Extrapolating a historical ratio assumes the relationship does not break down.",
'ct-48':"'Some reviewed items are rejected' proves review is necessary but not sufficient.",
'ct-49':"Untreated comparison areas rule out trends affecting everyone.",
'ct-50':"Adding people to a late project imposes coordination cost on the producers.",
'ct-51':"Performance without a benchmark is uninterpretable.",
'ct-52':"Comparing a recurring cost with an upfront one needs the asset's useful life.",
'ct-53':"Contractual lock-in means a short window cannot detect attrition.",
'ct-54':"Added capacity can induce new demand and restore the original congestion.",
'ct-55':"Affirming the consequent licenses no conclusion at all.",
'ct-56':"Independent verification converts an assertion into a substantiated estimate.",
'ct-57':"An older population means more real disease, not more over-diagnosis.",
'ct-58':"Total wait includes the decision phase, not just the production phase.",
'ct-59':"A remedy only works if it targets the actual cause of the problem.",
'ct-60':"When advantages travel together, no single one can be isolated as the cause.",
'ct-61':"With each remaining item capped, divide the remainder by the cap for the minimum count.",
'ct-62':"Profitability needs the cost side too, not just the revenue side.",
'ct-63':"Reach is an input metric; success is defined by the outcome.",
'ct-64':"Holding conditions constant is what makes a before-and-after comparison valid.",
'ct-65':"Excluding dropouts is survivorship bias and inflates the success rate.",
'ct-66':"'Only if' introduces necessary conditions — all of them must hold.",
'ct-67':"Improved availability draws in users from other channels; queues can lengthen.",
'ct-68':"Silence is not endorsement. Absence of objection is not evidence in favour.",
'ct-69':"Electric vehicles move emissions to the grid, so grid composition decides the benefit.",
'ct-70':"Popular does not mean paid for; readership need not convert into subscriptions.",
'ct-71':"A 'must be true' answer usually restates a premise in equivalent terms.",
'ct-72':"Check whether the metric captures the goal or a workaround for a new problem.",
'ct-73':"A treated-versus-untreated comparison isolates the intervention.",
'ct-74':"'Some A are B' plus 'all B are C' yields 'some A are C' — never 'all'.",
'ct-75':"Chain the conditionals: A → B → not-C gives A → not-C.",
'ct-76':"Two 'some' groups may not overlap at all. Nothing follows.",
'ct-77':"From 'no A are B' and 'all B are C', conclude 'some C are not A'.",
'ct-78':"A negative premise yields a negative conclusion, and only about 'some'.",
'ct-79':"Necessary is not sufficient — knowing the condition holds proves nothing.",
'ct-80':"A subset and an overlapping group need not intersect. Undetermined.",
'ct-81':"Contrapositive: 'passes → sent' gives 'not sent → did not pass'.",
'ct-82':"Chain the relative constraints into one order, then slot in whatever is fixed.",
'ct-83':"With few slots left, test each placement; a contradiction means backtrack.",
'ct-84':"When every constraint links two adjacent items, the whole ranking resolves.",
'ct-85':"Anchor on the fixed date first, then apply the negative constraints.",
'ct-86':"Place every stated constraint, then read off the one gap that remains.",
'ct-87':"Convert all comparisons into a single left-to-right ordering.",
'ct-88':"Letter sequences are number sequences: convert A=1 … Z=26 first.",
'ct-89':"Check the direction — a backwards alphabet sequence counts down.",
'ct-90':"For 'NOT valid', test every option against every rule.",
'ct-91':"Anchor on the one fixed date and count outwards to avoid off-by-one errors.",
'ct-92':"A strong argument is both directly relevant AND weighty enough to decide.",
'ct-93':"Measured internal data beats preference, habit and what other companies do.",
'ct-94':"Trial evidence of the outcome that matters outranks authority or enthusiasm.",
'ct-95':"Measured effects on the actual objective are what make an argument strong.",
'ct-96':"A documented track record of similar failures is directly relevant and decisive.",
'ct-97':"An argument can be true and still weak — weakness is about relevance and weight.",
'ct-98':"Being an estimate does not make an argument weak.",
'ct-99':"Popularity is a bandwagon appeal: it gives no reason to think the approach works.",

/* ================= ENGLISH ================= */
'eng-0':"Mitigate = make less severe. Not remove, not delay.",
'eng-1':"Feasible = doable. It says nothing about cost or simplicity.",
'eng-2':"Ambiguous = open to more than one reading. Ambivalent = having mixed feelings.",
'eng-3':"Scrutinize = examine closely. Summarize condenses; scrutinize expands attention.",
'eng-4':"Redundant = more than necessary.",
'eng-5':"Prudent = careful and sensible about the future.",
'eng-6':"Substantiate = back with evidence. Its opposite is refute.",
'eng-7':"Volatile = liable to sudden unpredictable change.",
'eng-8':"Consolidate = combine separate parts into one whole.",
'eng-9':"Obsolete = superseded by something newer, even if it still works.",
'eng-10':"Discrepancy = a mismatch between figures that should agree.",
'eng-11':"Meticulous = extremely careful with detail, and positive in tone.",
'eng-12':"Read the word OPPOSITE twice — the synonym is always offered as a distractor.",
'eng-13':"Comprehensive = complete. Comprehensible = understandable. One suffix apart.",
'eng-14':"An incentive encourages; a penalty discourages. Opposite mechanisms.",
'eng-15':"With neither…nor, the verb agrees with the NEARER subject.",
'eng-16':"Each, every, either and neither are singular as subjects.",
'eng-17':"'The number of' is singular; 'a number of' is plural.",
'eng-18':"'Along with' does not change the subject. Delete the phrase and check.",
'eng-19':"Neither = 'not one of the two', so it takes a singular verb.",
'eng-20':"'One of the X who…' — the relative clause agrees with the plural X.",
'eng-21':"The earlier of two past events takes the past perfect.",
'eng-22':"'Since' plus a start point requires the present perfect.",
'eng-23':"Second conditional: if + past simple, would + base verb.",
'eng-24':"Third conditional: if + past perfect, would have + participle.",
'eng-25':"A period completed before another past event takes the past perfect.",
'eng-26':"A future time marker requires 'will', not the present simple.",
'eng-27':"Suggest, recommend, insist, demand and require trigger the bare base form.",
'eng-28':"After any preposition, use the object pronoun: 'between you and me'.",
'eng-29':"Fewer for countable, less for uncountable.",
'eng-30':"'Despite' takes a noun phrase; 'although' takes a full clause.",
'eng-31':"After a preposition, use 'whom'. Test by substituting him/he.",
'eng-32':"Comparing exactly two things takes the comparative, not the superlative.",
'eng-33':"'Be used to' ends in a preposition, so a gerund follows.",
'eng-34':"'Look forward to' takes -ing, not the infinitive.",
'eng-35':"An opening participial phrase must describe the subject that follows the comma.",
'eng-36':"Items in a list must share one grammatical form.",
'eng-37':"Compare like with like: use 'that of' to stand in for the repeated noun.",
'eng-38':"'Not only… but also' must join grammatically equivalent elements.",
'eng-39':"The subject after the comma must be the one performing the opening action.",
'eng-40':"Formal English requires 'different from'.",
'eng-41':"Between for two; among for three or more.",
'eng-42':"'Revert back' is redundant — revert already means to go back.",
'eng-43':"An intervening relative clause does not change subject–verb agreement.",
'eng-44':"Every pronoun needs exactly one possible referent.",
'eng-45':"With neither…nor, agreement follows the nearer noun.",
'eng-46':"'Recommend that' takes the base form, not 'to do'.",
'eng-47':"Responsible FOR a task; responsible TO a person.",
'eng-48':"Consistent WITH.",
'eng-49':"Depend ON — never 'depend of'.",
'eng-50':"Comply WITH.",
'eng-51':"In charge OF.",
'eng-52':"Capable OF + -ing; able TO + base verb.",
'eng-53':"Result IN the consequence; result FROM the cause.",
'eng-54':"Concerned ABOUT = worried; concerned WITH = on the subject of.",
'eng-55':"Account FOR = explain; account TO = answer to a person.",
'eng-56':"Self-reported gains and measured gains are different claims.",
'eng-57':"Read both reported outcomes before choosing; trade-offs have two sides.",
'eng-58':"A methodological objection attacks what the evidence can prove, not the claim itself.",
'eng-59':"Check which side of a ratio actually moved before crediting a cause.",
'eng-60':"Find the mechanism the passage names, and the option it explicitly rules out.",
'eng-61':"'Value-destroying' means costs exceeded benefits — identify both sides.",
'eng-62':"A gain for one segment paired with a loss for another is a trade-off, not a failure.",
'eng-63':"Net the quantified figures; unquantified consequences stay as trade-offs.",
'eng-64':"'Given that' introduces a reason and takes a clause.",
'eng-65':"'However' marks contrast; 'therefore' marks consequence.",
'eng-66':"'In spite of' takes a noun phrase; 'even though' takes a clause.",
'eng-67':"'Provided that' attaches a condition.",
'eng-68':"'Had barely… when' is a fixed pair, as is 'no sooner… than'.",
'eng-69':"A relative clause must sit immediately after the noun it describes.",
'eng-70':"Concise and active beats long and passive. Cut 'due to the fact that'.",
'eng-71':"Two independent clauses need a semicolon or a conjunction, never a bare comma.",
'eng-72':"Put 'only' immediately before whatever it limits.",
'eng-73':"Keep one tense across a list of actions in the same sequence.",
'eng-74':"Streamline = simplify to run more efficiently, not merely speed up.",
'eng-75':"Contingent on = conditional upon, not proportional to.",
'eng-76':"Anticipate = expect. It does NOT mean to bring forward, unlike 'anticipar'.",
'eng-77':"A stakeholder is anyone affected, not only an investor.",
'eng-78':"Concise ↔ verbose. 'Brief' is a synonym, not the opposite.",
'eng-79':"Defer a decision = postpone it. Defer to a person = yield to them.",
'eng-80':"Robust = holds up when assumptions or methods change.",
'eng-81':"'Would have' in the main clause demands the past perfect after 'if'.",
'eng-82':"A parenthetical phrase between commas is not part of the subject.",
'eng-83':"'By [future time]' requires the future perfect.",
'eng-84':"'Insist that' triggers the subjunctive base form, passive included.",
'eng-85':"Strip out the prepositional phrase and the agreement becomes obvious.",
'eng-86':"After a comma, only 'which' can introduce a non-defining clause.",
'eng-87':"'Reduce down' is redundant — reduce already means to lower."

  };
  window.TAKEAWAYS = Object.assign(window.TAKEAWAYS || {}, T);
  /* Attach to the questions themselves so the renderer needs no special case. */
  Object.keys(window.QUESTION_BANK || {}).forEach(function(k){
    window.QUESTION_BANK[k].forEach(function(q){
      if(!q.takeaway && T[q.id]) q.takeaway = T[q.id];
    });
  });
})();
